### ISSUE TITLE
Temp file should be open in binary mode...?

### ISSUE THREAD

**Issue by boazadato** [sdsykes/fastimage_resize#3]
Hello

Running on ruby 1.9.2 + rails 3.1.2, i got Encoding::UndefinedConversionError exception when calling FastImage.resize.

Dug in, and found that filemode is not binary.

workaround - added 
**temp.binmode** 
to fastimage_resize.rb :: read_to_local

New method code:

```
def self.read_to_local(readable)
    temp = Tempfile.new(name)
    temp.binmode # <--
    temp.write(readable.read)
    temp.close
    temp.open
    temp
end
```

**Comment by shideneyu** [comment]
That fix is awesome. Thanks.
